import { Service, TeamMember, CaseStudy, Testimonial } from './types';

export const MARQUEE_CLIENTS = [
  'LUXURY MOOD',
  'NOT ORDINARY FAMILY',
  'MABILOFT',
  'TABLO',
  'CERTIBLOK',
  'SCRIPTIE',
  'SINCOSALD',
  'TESSERINI',
  'COLLEROCK',
  'SINTESI DESIGN',
  'G&G SALDATURA',
  'ACADEMY 4.0',
  'TOKALON',
  'TERESA ACADEMY',
  'H2R',
  'STANDUP',
  'ANTICA OSTERIA CERA',
  'SICURAMENTE FABIA',
];

export const SERVICES: Service[] = [
  {
    id: 'meta-ads',
    title: 'Meta Ads',
    description: 'Campagne pubblicitarie su Instagram e Facebook mirate all\'acquisizione di clienti pronti a comprare. Ottimizziamo il ROAS attraverso una segmentazione avanzata e creatività ad alto impatto.',
    category: 'advertising',
    tags: ['Facebook', 'Instagram', 'Targeting', 'Scale'],
  },
  {
    id: 'google-ads',
    title: 'Google Ads',
    description: 'Intercettiamo la domanda attiva degli utenti sui motori di ricerca. Strutturiamo campagne Search, Performance Max e Shopping per portare traffico ad altissima conversione sul tuo sito.',
    category: 'advertising',
    tags: ['Search', 'Shopping', 'PMax', 'Retargeting'],
  },
  {
    id: 'linkedin-ads',
    title: 'LinkedIn Ads',
    description: 'La soluzione ideale per agenzie e aziende B2B. Intercettiamo i decision maker e i professionisti del tuo settore per generare lead altamente qualificati.',
    category: 'advertising',
    tags: ['B2B', 'Lead Generation', 'Corporate'],
  },
  {
    id: 'tiktok-ads',
    title: 'TikTok Ads',
    description: 'Raggiungiamo le nuove generazioni con campagne video dinamiche e native. Perfetto per e-commerce e brand che vogliono scalare rapidamente con contenuti virali.',
    category: 'advertising',
    tags: ['Gen Z', 'Video Ads', 'Viral Content'],
  },
  {
    id: 'performance-creative',
    title: 'Performance Creative',
    description: 'Creiamo contenuti video e grafici esplicitamente progettati per convertire. Non facciamo "arte", facciamo creatività strategica testata per abbassare il costo di acquisizione.',
    category: 'content',
    tags: ['UGC', 'Hook Design', 'Direct Response'],
  },
  {
    id: 'social-media',
    title: 'Social Media Management',
    description: 'Gestione strategica della tua presenza organica sui social. Costruiamo una community fedele e posizioniamo il tuo brand come leader indiscusso del settore.',
    category: 'content',
    tags: ['Branding', 'Community', 'Content Plan'],
  },
  {
    id: 'email-marketing',
    title: 'Email Marketing & Automation',
    description: 'Strutturiamo flussi automatici (Flows) e newsletter editoriali per massimizzare il Lifetime Value dei tuoi clienti e recuperare carrelli abbandonati.',
    category: 'technical',
    tags: ['Klaviyo', 'Automations', 'Nurturing', 'Retention'],
  },
  {
    id: 'funnels',
    title: 'Funnels & Conversion Rate Optimization',
    description: 'Analizziamo e ristrutturiamo il percorso d\'acquisto del cliente. Eliminiamo i punti di frizione per raddoppiare il tasso di conversione del tuo traffico attuale.',
    category: 'strategy',
    tags: ['Frictionless', 'A/B Testing', 'User Experience'],
  },
  {
    id: 'landing-pages',
    title: 'Landing Pages & E-Commerce Web Design',
    description: 'Progettiamo e sviluppiamo pagine di atterraggio ultra-veloci e ottimizzate per la conversione da mobile. Integrate con tracciamenti di precisione per pixel e API.',
    category: 'technical',
    tags: ['Tailwind', 'Conversion-First', 'Fast Load', 'API Tracking'],
  },
  {
    id: 'video-production',
    title: 'Video Production & UGC',
    description: 'Scrittura, ripresa e montaggio di video verticali e spot aziendali. Coordiniamo una rete di creator per generare video UGC freschi ed estremamente autentici.',
    category: 'content',
    tags: ['Video Editing', 'UGC Network', 'Concept Development'],
  },
  {
    id: 'copywriting',
    title: 'Copywriting Persuasivo',
    description: 'Scriviamo testi che catturano l\'attenzione dei tuoi clienti ideali e li spingono all\'azione. Da titoli magnetici a descrizioni prodotto che eliminano ogni obiezione.',
    category: 'content',
    tags: ['Persuasione', 'Storytelling', 'Sales Copy'],
  },
  {
    id: 'strategia',
    title: 'Strategia di Marketing Omnichannel',
    description: 'Definiamo il piano d\'azione complessivo. Analisi di mercato, posizionamento, definizione dei canali e calcolo preciso del budget per una crescita sostenibile.',
    category: 'strategy',
    tags: ['Market Research', 'KPI Setup', 'Omnichannel Planning'],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'alessandro',
    name: 'Alessandro',
    role: 'Co-Founder & Head of Strategy',
    bio: 'Pianifica le strategie omnichannel per le PMI. Esperto di allocazione di budget pubblicitario e posizionamento di mercato.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'antonio',
    name: 'Antonio',
    role: 'Media Buyer Specialist',
    bio: 'Gestisce e ottimizza le campagne pubblicitarie su Meta e Google. Con oltre 3 milioni di euro amministrati, conosce ogni segreto dell\'algoritmo.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'david',
    name: 'David',
    role: 'Lead Developer & Automation Specialist',
    bio: 'Costruisce landing page velocissime e integra API di tracciamento avanzate per garantire che nessun dato vada perso.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'francesca',
    name: 'Francesca',
    role: 'Performance Copywriter',
    bio: 'Scrive messaggi che convertono. Traduce i punti di forza dei clienti in testi magnetici per annunci pubblicitari e funnel.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'isabel',
    name: 'Isabel',
    role: 'Creative Director',
    bio: 'Supervisiona la produzione di grafiche e video. Si assicura che ogni contenuto unisca l\'estetica del brand alla conversione.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'marco',
    name: 'Marco',
    role: 'Social Media & Community Manager',
    bio: 'Cura la presenza organica delle aziende. Costruisce relazioni reali con la community per aumentare la fidelizzazione spontanea.',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'matteo',
    name: 'Matteo',
    role: 'Video Maker & Editor',
    bio: 'Cattura l\'attenzione nei primi 3 secondi. Gira e monta video verticali UGC e spot ad alte prestazioni per le campagne.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'mirtilla',
    name: 'Mirtilla',
    role: 'Influencer Specialist & Communication',
    bio: 'Seleziona e coordina i migliori creator e influencer. Crea connessioni efficaci che portano fiducia immediata al brand.',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400',
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'case-luxury-mood',
    clientName: 'LUXURY MOOD',
    sector: 'Design & Arredamento di Lusso',
    title: 'Da zero a un sistema di lead generation automatizzato per arredi di alta gamma.',
    description: 'Abbiamo creato un funnel profilato per targetizzare architetti e clienti alto-spendenti. Attraverso una forte componente creativa video e landing page interattive, abbiamo generato lead pronti all\'acquisto senza sprecare budget.',
    results: [
      { label: 'Ritorno sull\'investimento (ROAS)', value: 'x5.4' },
      { label: 'Nuovi Lead Qualificati', value: '+1,240' },
      { label: 'Costo per Contatto Qualificato', value: '-38%' },
    ],
    teamMembers: ['Alessandro', 'Antonio', 'Francesca', 'Isabel'],
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=800&h=500',
  },
  {
    id: 'case-not-ordinary-family',
    clientName: 'NOT ORDINARY FAMILY',
    sector: 'E-commerce Abbigliamento streetwear',
    title: 'Scalare un brand di abbigliamento grazie a contenuti UGC e TikTok Ads.',
    description: 'Strategia incentrata sulla viralità e su contenuti autentici registrati dagli utenti (UGC). Sfruttando TikTok Ads e campagne di retargeting dinamiche su Meta, abbiamo superato il limite di fatturato mensile consolidato.',
    results: [
      { label: 'Incremento Fatturato', value: '+215%' },
      { label: 'Nuovi Clienti Acquisiti', value: '+3,850' },
      { label: 'Costo di Acquisizione (CAC)', value: '-42%' },
    ],
    teamMembers: ['Antonio', 'Matteo', 'Mirtilla', 'Isabel'],
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80&w=800&h=500',
  },
  {
    id: 'case-mabiloft',
    clientName: 'MABILOFT',
    sector: 'Real Estate & Hospitality',
    title: 'Saturazione delle prenotazioni per una catena di loft esclusivi.',
    description: 'Ottimizzazione del posizionamento locale ed e-mail automation per ricontattare i clienti storici. Abbiamo abbinato campagne Google Ads locali e Meta Ads geograficamente mirate per garantire il sold-out continuo.',
    results: [
      { label: 'Tasso di Occupazione', value: '98%' },
      { label: 'Prenotazioni Dirette (No OTA)', value: '+65%' },
      { label: 'Costo per Prenotazione', value: '-29%' },
    ],
    teamMembers: ['Alessandro', 'David', 'Marco', 'Francesca'],
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800&h=500',
  },
  {
    id: 'case-sincosald',
    clientName: 'SINCOSALD',
    sector: 'Industria & Saldatura Professionale B2B',
    title: 'Generazione contatti qualificati B2B per l\'industria metalmeccanica.',
    description: 'Un settore altamente specializzato richiede una strategia mirata su LinkedIn e Google Search. Abbiamo strutturato un lead magnet tecnico (un whitepaper di settore) per acquisire contatti di responsabili acquisti e titolari d\'officina.',
    results: [
      { label: 'Lead B2B Generati', value: '412' },
      { label: 'Tasso di Conversione Landing', value: '14.2%' },
      { label: 'Opportunità Commerciali Aperte', value: 'x3.2' },
    ],
    teamMembers: ['Alessandro', 'Antonio', 'David', 'Francesca'],
    imageUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=800&h=500',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Filippo Bernasconi',
    role: 'Titolare',
    company: 'Luxury Mood',
    quote: 'Mirtilla e il team di NGM ci hanno aperto gli occhi sul vero marketing. Prima spendevamo su Instagram a caso, ora abbiamo un flusso prevedibile di contatti ad alto valore che arrivano ogni settimana.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: 'test-2',
    name: 'Serena Marini',
    role: 'Brand Manager',
    company: 'Not Ordinary Family',
    quote: 'Lavorare con NGM è come avere un reparto marketing interno ma composto dai migliori specialisti del settore. Matteo e Isabel hanno trasformato i nostri video social, abbassando i costi pubblicitari del 42% in soli tre mesi.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: 'test-3',
    name: 'Ing. Roberto Sacco',
    role: 'CEO & Direttore Generale',
    company: 'Sincosald S.r.l.',
    quote: 'Eravamo scettici sull\'uso dei canali digitali per un prodotto B2B così tecnico. Alessandro e David hanno sviluppato una landing page eccezionale e una strategia su Google Ads che ci ha connesso con distributori in tutta Europa.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100&h=100',
  },
];
